"""restructuring database

Revision ID: 26185cbbf7d1
Revises: d027cebd3d0e
Create Date: 2025-07-02 21:17:37.495580

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "26185cbbf7d1"
down_revision: Union[str, None] = "d027cebd3d0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Создаем необходимые схемы, если они еще не существуют.
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS trader_core")

    # Включаем расширение для поддержки UUID, если его еще нет.
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    op.drop_index("ix_trade_stats_created_at", table_name="trade_stats")
    op.drop_table("trade_stats")
    op.drop_index("ix_signals_created_at", table_name="signals")
    op.drop_table("signals")
    op.drop_index(
        "ix_strategy_params_created_at", table_name="strategy_params"
    )
    op.drop_table("strategy_params")
    op.drop_index("ix_tickers_created_at", table_name="tickers")
    op.drop_table("tickers")
    op.drop_index("ix_markets_created_at", table_name="markets")
    op.drop_table("markets")
    op.drop_index("ix_strategies_created_at", table_name="strategies")
    op.drop_table("strategies")

    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "email",
            sa.String(length=254),
            nullable=False,
            comment="Email пользователя",
        ),
        sa.Column(
            "hashed_password",
            sa.String(length=128),
            nullable=False,
            comment="Хэш пароля пользователя",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время сохранения записи",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_users_created_at"),
        "users",
        ["created_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_users_email"),
        "users",
        ["email"],
        unique=True,
        schema="auth",
    )
    op.create_table(
        "indicators",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "indicator_key",
            sa.String(length=100),
            nullable=False,
            comment="Уникальный ключ индикатора, например, 'sma_20'",
        ),
        sa.Column(
            "name",
            sa.String(length=50),
            nullable=False,
            comment="Имя семейства индикаторов, например, 'SMA'",
        ),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Параметры индикатора в формате JSON",
        ),
        sa.Column(
            "is_hot",
            sa.Boolean(),
            nullable=False,
            comment="Флаг для RT-калькулятора",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trader_core",
    )
    op.create_index(
        op.f("ix_trader_core_indicators_indicator_key"),
        "indicators",
        ["indicator_key"],
        unique=True,
        schema="trader_core",
    )
    op.create_table(
        "markets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "market_code",
            sa.String(length=50),
            nullable=False,
            comment="Уникальный код рынка",
        ),
        sa.Column(
            "description",
            sa.String(length=255),
            nullable=False,
            comment="Описание торговой площадки",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trader_core",
    )
    op.create_index(
        op.f("ix_trader_core_markets_market_code"),
        "markets",
        ["market_code"],
        unique=True,
        schema="trader_core",
    )
    op.create_table(
        "strategies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id", sa.UUID(), nullable=False, comment="FK на auth.users"
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Название, данное пользователем",
        ),
        sa.Column(
            "definition",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="AST стратегии из no-code редактора",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время сохранения записи",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["auth.users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trader_core",
    )
    op.create_index(
        op.f("ix_trader_core_strategies_created_at"),
        "strategies",
        ["created_at"],
        unique=False,
        schema="trader_core",
    )
    op.create_index(
        op.f("ix_trader_core_strategies_user_id"),
        "strategies",
        ["user_id"],
        unique=False,
        schema="trader_core",
    )
    op.create_table(
        "tickers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "symbol",
            sa.String(length=50),
            nullable=False,
            comment="Символ инструмента (тикер)",
        ),
        sa.Column(
            "market_id",
            sa.Integer(),
            nullable=False,
            comment="FK на trader_core.markets",
        ),
        sa.Column(
            "description",
            sa.String(length=255),
            nullable=True,
            comment="Краткое название",
        ),
        sa.Column(
            "type",
            sa.Enum(
                "STOCK",
                "CURRENCY",
                "FUTURE",
                "OPTION",
                "BOND",
                name="ticker_type_enum",
                schema="trader_core",
            ),
            nullable=False,
            comment="Тип инструмента",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Флаг активности сбора данных",
        ),
        sa.Column(
            "lot_size", sa.Integer(), nullable=True, comment="Размер лота"
        ),
        sa.Column(
            "min_step",
            sa.Float(),
            nullable=True,
            comment="Минимальный шаг цены",
        ),
        sa.Column(
            "decimals", sa.Integer(), nullable=True, comment="Точность цены"
        ),
        sa.Column("isin", sa.String(length=12), nullable=True, comment="ISIN"),
        sa.Column(
            "currency",
            sa.String(length=10),
            nullable=True,
            comment="Валюта торгов",
        ),
        sa.ForeignKeyConstraint(
            ["market_id"], ["trader_core.markets.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isin"),
        sa.UniqueConstraint("symbol", "market_id", name="uq_symbol_market_id"),
        schema="trader_core",
    )
    op.create_index(
        op.f("ix_trader_core_tickers_symbol"),
        "tickers",
        ["symbol"],
        unique=False,
        schema="trader_core",
    )
    op.create_table(
        "backtest_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("strategy_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ticker", sa.String(length=50), nullable=False),
        sa.Column("timeframe", sa.String(length=10), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CALCULATING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="job_status_enum",
                schema="trader_core",
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время сохранения записи",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"], ["trader_core.strategies.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["auth.users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trader_core",
    )
    op.create_index(
        op.f("ix_trader_core_backtest_jobs_created_at"),
        "backtest_jobs",
        ["created_at"],
        unique=False,
        schema="trader_core",
    )
    op.create_index(
        op.f("ix_trader_core_backtest_jobs_status"),
        "backtest_jobs",
        ["status"],
        unique=False,
        schema="trader_core",
    )

    # Предзаполнение данных
    op.execute(
        """
        INSERT INTO trader_core.markets (market_code, description) VALUES
        ('moex_stock', 'Московская биржа - Фондовый рынок'),
        ('moex_currency', 'Московская биржа - Валютный рынок'),
        ('bybit_futures', 'Bybit - Бессрочные фьючерсы');
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Откатывает изменения, воссоздавая предыдущую структуру базы данных.
    Операции выполняются в строгом обратном порядке для соблюдения зависимостей.
    """
    # ### Шаг 1: Удаляем новые таблицы и объекты в обратном порядке ###
    # Сначала удаляем таблицы, которые зависят от других
    op.drop_index(
        op.f("ix_trader_core_backtest_jobs_status"),
        table_name="backtest_jobs",
        schema="trader_core",
    )
    op.drop_index(
        op.f("ix_trader_core_backtest_jobs_created_at"),
        table_name="backtest_jobs",
        schema="trader_core",
    )
    op.drop_table("backtest_jobs", schema="trader_core")

    op.drop_index(
        op.f("ix_trader_core_strategies_user_id"),
        table_name="strategies",
        schema="trader_core",
    )
    op.drop_index(
        op.f("ix_trader_core_strategies_created_at"),
        table_name="strategies",
        schema="trader_core",
    )
    op.drop_table("strategies", schema="trader_core")

    op.drop_index(
        op.f("ix_trader_core_tickers_symbol"),
        table_name="tickers",
        schema="trader_core",
    )
    op.drop_table("tickers", schema="trader_core")

    # Затем удаляем таблицы, от которых зависели другие
    op.drop_index(
        op.f("ix_trader_core_markets_market_code"),
        table_name="markets",
        schema="trader_core",
    )
    op.drop_table("markets", schema="trader_core")

    op.drop_index(
        op.f("ix_trader_core_indicators_indicator_key"),
        table_name="indicators",
        schema="trader_core",
    )
    op.drop_table("indicators", schema="trader_core")

    op.drop_index(
        op.f("ix_auth_users_email"), table_name="users", schema="auth"
    )
    op.drop_index(
        op.f("ix_auth_users_created_at"), table_name="users", schema="auth"
    )
    op.drop_table("users", schema="auth")

    # Удаляем Enum типы, созданные Alembic (если они есть)
    # Alembic создает их с именем, которое вы указали в модели
    op.execute("DROP TYPE IF EXISTS trader_core.ticker_type_enum;")
    op.execute("DROP TYPE IF EXISTS trader_core.job_status_enum;")

    # Удаляем схемы, только если они пусты
    op.execute("DROP SCHEMA IF EXISTS trader_core CASCADE")
    op.execute("DROP SCHEMA IF EXISTS auth CASCADE")

    # ### Шаг 2: Воссоздаем старые таблицы в правильном порядке ###
    # Сначала создаем таблицы без внешних ключей или те, на которые будут ссылаться
    op.create_table(
        "markets",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.VARCHAR(length=128),
            nullable=False,
            comment="Название рынка (биржи)",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="markets_pkey"),
        sa.UniqueConstraint("name", name="markets_name_key"),
    )
    op.create_index(
        "ix_markets_created_at", "markets", ["created_at"], unique=False
    )

    op.create_table(
        "strategies",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.VARCHAR(length=128),
            nullable=False,
            comment="Название стратегии",
        ),
        sa.Column(
            "description",
            sa.VARCHAR(length=500),
            nullable=True,
            comment="Описание стратегии",
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=128),
            server_default=sa.text("'CREATED'::character varying"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="strategies_pkey"),
        sa.UniqueConstraint("name", name="strategies_name_key"),
    )
    op.create_index(
        "ix_strategies_created_at", "strategies", ["created_at"], unique=False
    )

    # Затем создаем таблицы, которые зависят от предыдущих
    op.create_table(
        "tickers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "market",
            sa.VARCHAR(length=128),
            nullable=False,
            comment="FK на markets",
        ),
        sa.Column(
            "symbol",
            sa.VARCHAR(length=128),
            nullable=False,
            comment="Символ инструмента (например, BTCUSDT)",
        ),
        sa.Column(
            "description",
            sa.VARCHAR(length=500),
            nullable=True,
            comment="Доп. описание тикера",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["market"], ["markets.name"], name="tickers_market_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="tickers_pkey"),
        sa.UniqueConstraint("symbol", name="tickers_symbol_key"),
    )
    op.create_index(
        "ix_tickers_created_at", "tickers", ["created_at"], unique=False
    )

    # Теперь можно создавать таблицы, ссылающиеся на strategies и tickers
    op.create_table(
        "signals",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("strategy_name", sa.VARCHAR(length=128), nullable=False),
        sa.Column("ticker", sa.VARCHAR(length=128), nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=50), nullable=False),
        sa.Column("signal_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("price", sa.NUMERIC(precision=20, scale=8), nullable=False),
        sa.Column(
            "stop_loss", sa.NUMERIC(precision=20, scale=8), nullable=True
        ),
        sa.Column("candle_time", postgresql.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["strategy_name"],
            ["strategies.name"],
            name="signals_strategy_name_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["ticker"], ["tickers.symbol"], name="signals_ticker_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="signals_pkey"),
    )
    op.create_index(
        "ix_signals_created_at", "signals", ["created_at"], unique=False
    )

    op.create_table(
        "strategy_params",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("strategy_name", sa.VARCHAR(length=128), nullable=False),
        sa.Column("ticker", sa.VARCHAR(length=128), nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=50), nullable=False),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "valid_from",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("valid_to", postgresql.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["strategy_name"],
            ["strategies.name"],
            name="strategy_params_strategy_name_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["ticker"], ["tickers.symbol"], name="strategy_params_ticker_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="strategy_params_pkey"),
    )
    op.create_index(
        "ix_strategy_params_created_at",
        "strategy_params",
        ["created_at"],
        unique=False,
    )

    op.create_table(
        "trade_stats",
        # Полное определение таблицы trade_stats из вашего старого кода...
        # ... я скопирую его из вашего файла для полноты.
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(), nullable=True),
        sa.Column("open_time", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("close_time", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("total_trades", sa.INTEGER(), nullable=True),
        sa.Column("wins", sa.INTEGER(), nullable=True),
        sa.Column("losses", sa.INTEGER(), nullable=True),
        sa.Column("win_rate", sa.NUMERIC(precision=5, scale=2), nullable=True),
        sa.Column(
            "profit_factor", sa.NUMERIC(precision=8, scale=4), nullable=True
        ),
        sa.Column("max_consecutive_wins", sa.INTEGER(), nullable=True),
        sa.Column("max_consecutive_losses", sa.INTEGER(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("strategy_name", sa.VARCHAR(length=128), nullable=False),
        sa.Column("ticker", sa.VARCHAR(length=128), nullable=False),
        sa.Column("position_type", sa.VARCHAR(), nullable=True),
        sa.Column(
            "entry_price", sa.NUMERIC(precision=20, scale=8), nullable=True
        ),
        sa.Column(
            "exit_price", sa.NUMERIC(precision=20, scale=8), nullable=True
        ),
        sa.Column(
            "stop_loss", sa.NUMERIC(precision=20, scale=8), nullable=True
        ),
        sa.Column(
            "profit_pct", sa.NUMERIC(precision=10, scale=4), nullable=True
        ),
        sa.Column(
            "profit_abs", sa.NUMERIC(precision=20, scale=8), nullable=True
        ),
        sa.Column("is_win", sa.BOOLEAN(), nullable=True),
        sa.Column(
            "duration_hours", sa.DOUBLE_PRECISION(precision=53), nullable=True
        ),
        sa.Column(
            "total_profit_pct",
            sa.NUMERIC(precision=10, scale=4),
            nullable=True,
        ),
        sa.Column(
            "total_profit_abs",
            sa.NUMERIC(precision=20, scale=8),
            nullable=True,
        ),
        sa.Column(
            "avg_profit_pct", sa.NUMERIC(precision=10, scale=4), nullable=True
        ),
        sa.Column("consecutive_wins", sa.INTEGER(), nullable=True),
        sa.Column("consecutive_losses", sa.INTEGER(), nullable=True),
        sa.Column(
            "best_trade_pct", sa.NUMERIC(precision=10, scale=4), nullable=True
        ),
        sa.Column(
            "worst_trade_pct", sa.NUMERIC(precision=10, scale=4), nullable=True
        ),
        sa.Column(
            "sum_win_abs", sa.NUMERIC(precision=20, scale=8), nullable=True
        ),
        sa.Column(
            "sum_loss_abs", sa.NUMERIC(precision=20, scale=8), nullable=True
        ),
        sa.Column(
            "sum_win_pct", sa.NUMERIC(precision=10, scale=4), nullable=True
        ),
        sa.Column(
            "sum_loss_pct", sa.NUMERIC(precision=10, scale=4), nullable=True
        ),
        sa.Column(
            "avg_win_pct", sa.NUMERIC(precision=10, scale=4), nullable=True
        ),
        sa.Column(
            "avg_loss_pct", sa.NUMERIC(precision=10, scale=4), nullable=True
        ),
        sa.Column(
            "total_duration_hours",
            sa.DOUBLE_PRECISION(precision=53),
            nullable=True,
        ),
        sa.Column(
            "avg_duration_hours",
            sa.DOUBLE_PRECISION(precision=53),
            nullable=True,
        ),
        sa.Column(
            "max_drawdown_pct",
            sa.NUMERIC(precision=10, scale=4),
            nullable=True,
        ),
        sa.Column(
            "current_drawdown_streak_pct",
            sa.NUMERIC(precision=10, scale=4),
            nullable=True,
        ),
        sa.Column(
            "profit_std_dev", sa.DOUBLE_PRECISION(precision=53), nullable=True
        ),
        sa.Column(
            "stability_score", sa.DOUBLE_PRECISION(precision=53), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["strategy_name"],
            ["strategies.name"],
            name="fk_trade_stats_strategy_name",
        ),
        sa.ForeignKeyConstraint(
            ["ticker"], ["tickers.symbol"], name="fk_trade_stats_ticker_symbol"
        ),
        sa.PrimaryKeyConstraint("id", name="trade_stats_pkey"),
    )
    op.create_index(
        "ix_trade_stats_created_at",
        "trade_stats",
        ["created_at"],
        unique=False,
    )
