"""add user session management

Revision ID: 06f314d0a1f6
Revises: 1f3b1e040702
Create Date: 2025-09-18 07:29:35.236078

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "06f314d0a1f6"
down_revision: Union[str, None] = "1f3b1e040702"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_blacklist",
        sa.Column(
            "token_jti",
            sa.String(length=255),
            nullable=False,
            comment="JWT ID (JTI) заблокированного токена",
        ),
        sa.Column(
            "token_type",
            sa.Enum("access", "refresh", name="token_type_enum"),
            nullable=False,
            comment="Тип токена: access или refresh",
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="ID пользователя, владельца токена",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Время истечения токена (для автоочистки)",
        ),
        sa.Column(
            "reason",
            sa.String(length=100),
            nullable=True,
            comment="Причина блокировки токена",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время сохранения записи",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время обновления записи",
        ),
        sa.PrimaryKeyConstraint("token_jti"),
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_token_blacklist_created_at"),
        "token_blacklist",
        ["created_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_token_blacklist_expires_at"),
        "token_blacklist",
        ["expires_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_token_blacklist_user_id"),
        "token_blacklist",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "user_sessions",
        sa.Column(
            "session_id",
            sa.UUID(),
            nullable=False,
            comment="Уникальный идентификатор сессии",
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="ID пользователя, владельца сессии",
        ),
        sa.Column(
            "refresh_token_jti",
            sa.String(length=255),
            nullable=False,
            comment="JWT ID (JTI) текущего refresh токена сессии",
        ),
        sa.Column(
            "device_name",
            sa.String(length=255),
            nullable=True,
            comment="Название устройства (например, 'MacBook Pro')",
        ),
        sa.Column(
            "device_type",
            sa.String(length=50),
            nullable=True,
            comment="Тип устройства: desktop, mobile, tablet",
        ),
        sa.Column(
            "user_agent",
            sa.Text(),
            nullable=True,
            comment="User-Agent браузера",
        ),
        sa.Column(
            "ip_address",
            postgresql.INET(),
            nullable=True,
            comment="IP адрес клиента",
        ),
        sa.Column(
            "location_country",
            sa.String(length=100),
            nullable=True,
            comment="Страна по геолокации IP",
        ),
        sa.Column(
            "location_city",
            sa.String(length=100),
            nullable=True,
            comment="Город по геолокации IP",
        ),
        sa.Column(
            "csrf_token",
            sa.String(length=255),
            nullable=True,
            comment="CSRF токен для защиты от межсайтовых атак",
        ),
        sa.Column(
            "last_activity",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последней активности в сессии",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Время истечения сессии",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Активна ли сессия",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время сохранения записи",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["auth.users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("session_id"),
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_user_sessions_created_at"),
        "user_sessions",
        ["created_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_user_sessions_expires_at"),
        "user_sessions",
        ["expires_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_user_sessions_ip_address"),
        "user_sessions",
        ["ip_address"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_user_sessions_last_activity"),
        "user_sessions",
        ["last_activity"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_user_sessions_refresh_token_jti"),
        "user_sessions",
        ["refresh_token_jti"],
        unique=True,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_user_sessions_user_id"),
        "user_sessions",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "security_events",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Уникальный идентификатор события",
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=True,
            comment="ID пользователя (может быть NULL для анонимных событий)",
        ),
        sa.Column(
            "session_id",
            sa.UUID(),
            nullable=True,
            comment="ID сессии (если событие связано с сессией)",
        ),
        sa.Column(
            "event_type",
            sa.String(length=100),
            nullable=False,
            comment="Тип события: login, logout, token_refresh, suspicious_activity, etc.",
        ),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Дополнительные детали события в JSON формате",
        ),
        sa.Column(
            "ip_address",
            postgresql.INET(),
            nullable=True,
            comment="IP адрес, с которого произошло событие",
        ),
        sa.Column(
            "user_agent",
            sa.Text(),
            nullable=True,
            comment="User-Agent браузера",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время сохранения записи",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["auth.user_sessions.session_id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["auth.users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_security_events_created_at"),
        "security_events",
        ["created_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_security_events_event_type"),
        "security_events",
        ["event_type"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_security_events_ip_address"),
        "security_events",
        ["ip_address"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_security_events_user_id"),
        "security_events",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_auth_security_events_user_id"),
        table_name="security_events",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_security_events_ip_address"),
        table_name="security_events",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_security_events_event_type"),
        table_name="security_events",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_security_events_created_at"),
        table_name="security_events",
        schema="auth",
    )
    op.drop_table("security_events", schema="auth")
    op.drop_index(
        op.f("ix_auth_user_sessions_user_id"),
        table_name="user_sessions",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_user_sessions_refresh_token_jti"),
        table_name="user_sessions",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_user_sessions_last_activity"),
        table_name="user_sessions",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_user_sessions_ip_address"),
        table_name="user_sessions",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_user_sessions_expires_at"),
        table_name="user_sessions",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_user_sessions_created_at"),
        table_name="user_sessions",
        schema="auth",
    )
    op.drop_table("user_sessions", schema="auth")
    op.drop_index(
        op.f("ix_auth_token_blacklist_user_id"),
        table_name="token_blacklist",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_token_blacklist_expires_at"),
        table_name="token_blacklist",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_token_blacklist_created_at"),
        table_name="token_blacklist",
        schema="auth",
    )
    op.drop_table("token_blacklist", schema="auth")
    # ### end Alembic commands ###
