"""add ticker columns

Revision ID: febb370167ba
Revises: d246e5058301
Create Date: 2025-08-31 19:17:14.552536

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "febb370167ba"
down_revision: Union[str, None] = "d246e5058301"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tickers",
        sa.Column(
            "short_name",
            sa.String(length=100),
            nullable=True,
            comment="Короткое имя",
        ),
        schema="trader_core",
    )
    op.add_column(
        "tickers",
        sa.Column(
            "list_level",
            sa.Integer(),
            nullable=True,
            comment="Уровень листинга",
        ),
        schema="trader_core",
    )
    op.execute(
        """
        DELETE FROM trader_core.markets m
        WHERE m.market_code = 'bybit_futures';
    """
    )

    # Исправление ENUM с UPPERCASE на lowercase

    # Переименовываем старый ENUM
    op.execute(
        "ALTER TYPE trader_core.ticker_type_enum RENAME TO ticker_type_enum_old;"
    )

    # Создаем новый, правильный ENUM с значениями в нижнем регистре
    op.execute(
        "CREATE TYPE trader_core.ticker_type_enum AS ENUM('stock', 'currency', 'future', 'option', 'bond');"
    )

    # Изменяем тип колонки, преобразуя старые значения в новые
    op.execute(
        """
        ALTER TABLE trader_core.tickers
        ALTER COLUMN type TYPE trader_core.ticker_type_enum
        USING LOWER(type::text)::trader_core.ticker_type_enum
    """
    )

    # Удаляем старый ENUM
    op.execute("DROP TYPE trader_core.ticker_type_enum_old;")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickers", "list_level", schema="trader_core")
    op.drop_column("tickers", "short_name", schema="trader_core")
    op.execute(
        """
        INSERT INTO trader_core.markets (market_code, description) VALUES
        ('bybit_futures', 'Bybit - Бессрочные фьючерсы');
    """
    )

    # Шаг 1: Переименовываем текущий ENUM в временный
    op.execute(
        "ALTER TYPE trader_core.ticker_type_enum RENAME TO ticker_type_enum_new;"
    )

    # Шаг 2: Создаем старый ENUM с значениями в верхнем регистре
    op.execute(
        "CREATE TYPE trader_core.ticker_type_enum AS ENUM('STOCK', 'CURRENCY', 'FUTURE', 'OPTION', 'BOND');"
    )

    # Шаг 3: Изменяем тип колонки обратно, преобразуя значения в верхний регистр
    op.execute(
        """
        ALTER TABLE trader_core.tickers
        ALTER COLUMN type TYPE trader_core.ticker_type_enum
        USING UPPER(type::text)::trader_core.ticker_type_enum
    """
    )

    # Шаг 4: Удаляем временный ENUM
    op.execute("DROP TYPE trader_core.ticker_type_enum_new;")
    # ### end Alembic commands ###
