"""remove unique key strategies

Revision ID: 1f3b1e040702
Revises: ed7a1f6878b8
Create Date: 2025-09-12 19:37:56.307529

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f3b1e040702"
down_revision: Union[str, None] = "ed7a1f6878b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_user_id_name", "strategies", schema="trader_core", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_id_name",
        "strategies",
        ["user_id", "name"],
        schema="trader_core",
    )
    # ### end Alembic commands ###
