"""add timezone to backtest_jobs table

Revision ID: 97466257268a
Revises: da5a7530fd9e
Create Date: 2025-09-28 14:51:41.925510

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "97466257268a"
down_revision: Union[str, None] = "da5a7530fd9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "backtest_batches",
        "estimated_completion_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        schema="trader_core",
    )
    op.alter_column(
        "backtest_jobs",
        "start_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        schema="trader_core",
    )
    op.alter_column(
        "backtest_jobs",
        "end_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        schema="trader_core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "backtest_jobs",
        "end_date",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        schema="trader_core",
    )
    op.alter_column(
        "backtest_jobs",
        "start_date",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        schema="trader_core",
    )
    op.alter_column(
        "backtest_batches",
        "estimated_completion_time",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        schema="trader_core",
    )
    # ### end Alembic commands ###
