"""add backtest_batches

Revision ID: da5a7530fd9e
Revises: ece52a1b42cd
Create Date: 2025-09-27 21:15:54.706216

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "da5a7530fd9e"
down_revision: Union[str, None] = "ece52a1b42cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Создание таблицы backtest_batches и связанных объектов."""
    connection = op.get_bind()

    # Проверяем существование enum типа и создаем только если его нет
    check_enum_query = """
        SELECT 1 FROM pg_type t 
        JOIN pg_namespace n ON n.oid = t.typnamespace 
        WHERE t.typname = 'batch_status_enum' AND n.nspname = 'trader_core'
    """

    result = connection.execute(sa.text(check_enum_query)).fetchone()

    if not result:
        # Создаем enum тип вручную через SQL
        connection.execute(
            sa.text(
                """
            CREATE TYPE trader_core.batch_status_enum AS ENUM (
                'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIALLY_FAILED'
            )
        """
            )
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.String(20),  # Временно используем String
            nullable=False,
            server_default="PENDING",
        ),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column(
            "completed_count", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column(
            "failed_count", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column("estimated_completion_time", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время сохранения записи",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["auth.users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trader_core",
    )

    # Изменяем тип колонки status на enum
    # Сначала удаляем default значение
    connection.execute(
        sa.text(
            """
        ALTER TABLE trader_core.backtest_batches
        ALTER COLUMN status DROP DEFAULT
    """
        )
    )

    # Меняем тип колонки
    connection.execute(
        sa.text(
            """
        ALTER TABLE trader_core.backtest_batches
        ALTER COLUMN status TYPE trader_core.batch_status_enum
        USING status::trader_core.batch_status_enum
    """
        )
    )

    # Устанавливаем новый default
    connection.execute(
        sa.text(
            """
        ALTER TABLE trader_core.backtest_batches
        ALTER COLUMN status SET DEFAULT 'PENDING'::trader_core.batch_status_enum
    """
        )
    )

    op.create_index(
        "idx_backtest_batches_user_sorting",
        "backtest_batches",
        ["user_id", "created_at", "status"],
        unique=False,
        schema="trader_core",
    )
    op.create_index(
        op.f("ix_trader_core_backtest_batches_created_at"),
        "backtest_batches",
        ["created_at"],
        unique=False,
        schema="trader_core",
    )
    op.create_index(
        op.f("ix_trader_core_backtest_batches_status"),
        "backtest_batches",
        ["status"],
        unique=False,
        schema="trader_core",
    )
    op.add_column(
        "backtest_jobs",
        sa.Column("batch_id", sa.UUID(), nullable=True),
        schema="trader_core",
    )
    op.create_index(
        "idx_backtest_jobs_batch",
        "backtest_jobs",
        ["batch_id", "created_at"],
        unique=False,
        schema="trader_core",
    )
    op.create_index(
        op.f("ix_trader_core_backtest_jobs_batch_id"),
        "backtest_jobs",
        ["batch_id"],
        unique=False,
        schema="trader_core",
    )
    op.create_foreign_key(
        None,
        "backtest_jobs",
        "backtest_batches",
        ["batch_id"],
        ["id"],
        source_schema="trader_core",
        referent_schema="trader_core",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Удаление таблицы backtest_batches и связанных объектов."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "backtest_jobs_batch_id_fkey",
        "backtest_jobs",
        schema="trader_core",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_trader_core_backtest_jobs_batch_id"),
        table_name="backtest_jobs",
        schema="trader_core",
    )
    op.drop_index(
        "idx_backtest_jobs_batch",
        table_name="backtest_jobs",
        schema="trader_core",
    )
    op.drop_column("backtest_jobs", "batch_id", schema="trader_core")
    op.drop_index(
        op.f("ix_trader_core_backtest_batches_status"),
        table_name="backtest_batches",
        schema="trader_core",
    )
    op.drop_index(
        op.f("ix_trader_core_backtest_batches_created_at"),
        table_name="backtest_batches",
        schema="trader_core",
    )
    op.drop_index(
        "idx_backtest_batches_user_sorting",
        table_name="backtest_batches",
        schema="trader_core",
    )
    op.drop_table("backtest_batches", schema="trader_core")

    # Проверяем существование enum типа и удаляем только если он есть
    connection = op.get_bind()

    check_enum_query = """
        SELECT 1 FROM pg_type t 
        JOIN pg_namespace n ON n.oid = t.typnamespace 
        WHERE t.typname = 'batch_status_enum' AND n.nspname = 'trader_core'
    """

    result = connection.execute(sa.text(check_enum_query)).fetchone()

    if result:
        # Проверяем, что enum не используется в других таблицах
        usage_check_query = """
            SELECT 1 FROM information_schema.columns 
            WHERE table_schema = 'trader_core' 
            AND udt_name = 'batch_status_enum'
            AND table_name != 'backtest_batches'
        """

        usage_result = connection.execute(
            sa.text(usage_check_query)
        ).fetchone()

        if not usage_result:
            connection.execute(
                sa.text("DROP TYPE trader_core.batch_status_enum")
            )
    # ### end Alembic commands ###
