"""add_admin_and_subscription_fields

Revision ID: ece52a1b42cd
Revises: f5d6bb049a9a
Create Date: 2025-09-25 21:42:40.165874

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ece52a1b42cd"
down_revision: Union[str, None] = "f5d6bb049a9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("FALSE"),
            comment="Является ли пользователь администратором",
        ),
        schema="auth",
    )
    op.add_column(
        "users",
        sa.Column(
            "subscription_tier",
            sa.String(length=20),
            nullable=False,
            server_default="free",
            comment="Тарифный план пользователя (free, pro, enterprise)",
        ),
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "subscription_tier", schema="auth")
    op.drop_column("users", "is_admin", schema="auth")
    # ### end Alembic commands ###
