"""update users table

Revision ID: 08b4091a9ad3
Revises: f9f5fd036065
Create Date: 2025-09-07 15:13:08.885394

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08b4091a9ad3"
down_revision: Union[str, None] = "f9f5fd036065"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("TRUE"),
            nullable=False,
            comment="Активен ли пользователь",
        ),
        schema="auth",
    )
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at", schema="auth")
    op.drop_column("users", "is_active", schema="auth")
    # ### end Alembic commands ###
