"""create tables

Revision ID: d602d581b5c7
Revises: 
Create Date: 2025-03-09 19:17:51.211627

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d602d581b5c7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "markets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.String(length=128),
            nullable=False,
            comment="Название рынка (биржи)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время сохранения записи",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_markets_created_at"), "markets", ["created_at"], unique=False
    )
    op.create_table(
        "strategies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.String(length=128),
            nullable=False,
            comment="Название стратегии",
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=True,
            comment="Описание стратегии",
        ),
        sa.Column(
            "status",
            sa.String(length=128),
            server_default="CREATED",
            nullable=False,
            comment="Статус стратегии",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время сохранения записи",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_strategies_created_at"),
        "strategies",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "tickers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "market",
            sa.String(length=128),
            nullable=False,
            comment="FK на markets",
        ),
        sa.Column(
            "symbol",
            sa.String(length=128),
            nullable=False,
            comment="Символ инструмента (например, BTCUSDT)",
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=True,
            comment="Доп. описание тикера",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время сохранения записи",
        ),
        sa.ForeignKeyConstraint(
            ["market"],
            ["markets.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol"),
    )
    op.create_index(
        op.f("ix_tickers_created_at"), "tickers", ["created_at"], unique=False
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "strategy_name",
            sa.String(length=128),
            nullable=False,
            comment="FK на таблицу strategies",
        ),
        sa.Column(
            "ticker",
            sa.String(length=128),
            nullable=False,
            comment="FK на таблицу tickers",
        ),
        sa.Column(
            "timeframe",
            sa.String(length=50),
            nullable=False,
            comment="Таймфрейм сигнала",
        ),
        sa.Column(
            "signal_type",
            sa.String(length=50),
            nullable=False,
            comment="Тип сигнала (BUY, SELL, MODIFY_SL и т.д.)",
        ),
        sa.Column(
            "price",
            sa.Numeric(precision=20, scale=8),
            nullable=False,
            comment="Цена входа / цены сигнала",
        ),
        sa.Column(
            "stop_loss",
            sa.Numeric(precision=20, scale=8),
            nullable=True,
            comment="Стоп-лосс, если есть",
        ),
        sa.Column(
            "candle_time",
            sa.DateTime(),
            nullable=True,
            comment="Время свечи, по которой сгенерирован сигнал",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время сохранения записи",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_name"],
            ["strategies.name"],
        ),
        sa.ForeignKeyConstraint(
            ["ticker"],
            ["tickers.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_signals_created_at"), "signals", ["created_at"], unique=False
    )
    op.create_table(
        "strategy_params",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "strategy_name",
            sa.String(length=128),
            nullable=False,
            comment="FK на таблицу strategies",
        ),
        sa.Column(
            "ticker",
            sa.String(length=128),
            nullable=False,
            comment="FK на таблицу tickers",
        ),
        sa.Column(
            "timeframe",
            sa.String(length=50),
            nullable=False,
            comment="Таймфрейм (например, 1h, 15m)",
        ),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="JSON с параметрами стратегии",
        ),
        sa.Column(
            "valid_from",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Дата, с которой параметры начинают действовать",
        ),
        sa.Column(
            "valid_to",
            sa.DateTime(),
            nullable=True,
            comment="Дата, по которую параметры действуют",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время сохранения записи",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_name"],
            ["strategies.name"],
        ),
        sa.ForeignKeyConstraint(
            ["ticker"],
            ["tickers.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_strategy_params_created_at"),
        "strategy_params",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "trade_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "strategy_id",
            sa.Integer(),
            nullable=False,
            comment="FK на таблицу strategies",
        ),
        sa.Column(
            "ticker_id",
            sa.Integer(),
            nullable=False,
            comment="FK на таблицу tickers",
        ),
        sa.Column(
            "timeframe",
            sa.String(),
            nullable=True,
            comment="Таймфрейм сделки или бэктеста",
        ),
        sa.Column(
            "open_time",
            sa.DateTime(),
            nullable=True,
            comment="Время открытия сделки",
        ),
        sa.Column(
            "close_time",
            sa.DateTime(),
            nullable=True,
            comment="Время закрытия сделки",
        ),
        sa.Column(
            "pnl",
            sa.Numeric(precision=20, scale=8),
            nullable=True,
            comment="Прибыль/убыток сделки",
        ),
        sa.Column(
            "start_date",
            sa.DateTime(),
            nullable=True,
            comment="Начало периода (например, начало бэктеста)",
        ),
        sa.Column(
            "end_date",
            sa.DateTime(),
            nullable=True,
            comment="Конец периода (например, конец бэктеста)",
        ),
        sa.Column(
            "initial_balance",
            sa.Numeric(precision=20, scale=8),
            nullable=True,
            comment="Начальный баланс в начале периода",
        ),
        sa.Column(
            "final_balance",
            sa.Numeric(precision=20, scale=8),
            nullable=True,
            comment="Конечный баланс в конце периода",
        ),
        sa.Column(
            "total_trades",
            sa.Integer(),
            nullable=True,
            comment="Всего сделок за период",
        ),
        sa.Column(
            "wins",
            sa.Integer(),
            nullable=True,
            comment="Кол-во выигрышных сделок",
        ),
        sa.Column(
            "losses",
            sa.Integer(),
            nullable=True,
            comment="Кол-во проигрышных сделок",
        ),
        sa.Column(
            "win_rate",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="Win-Rate (%)",
        ),
        sa.Column(
            "roi",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="ROI (%)",
        ),
        sa.Column(
            "max_drawdown_abs",
            sa.Numeric(precision=20, scale=8),
            nullable=True,
            comment="Макс. просадка в абсолюте",
        ),
        sa.Column(
            "max_drawdown_pct",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="Макс. просадка в процентах",
        ),
        sa.Column(
            "calmar",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="Calmar Ratio",
        ),
        sa.Column(
            "sharpe_ratio",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="Sharpe Ratio (упрощенный)",
        ),
        sa.Column(
            "profit_factor",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="Profit Factor",
        ),
        sa.Column(
            "avg_trade_profit",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="Средняя прибыль на сделку (в денежном выражении)",
        ),
        sa.Column(
            "avg_win",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="Средний выигрыш",
        ),
        sa.Column(
            "avg_loss",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="Средний проигрыш",
        ),
        sa.Column(
            "avg_ret",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="Средняя доходность сделки (%)",
        ),
        sa.Column(
            "median_ret",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="Медиана доходности сделки (%)",
        ),
        sa.Column(
            "std_ret",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="Стандартное отклонение доходности сделки (%)",
        ),
        sa.Column(
            "max_consecutive_wins",
            sa.Integer(),
            nullable=True,
            comment="Макс. подряд выигрышных сделок",
        ),
        sa.Column(
            "max_consecutive_losses",
            sa.Integer(),
            nullable=True,
            comment="Макс. подряд проигрышных сделок",
        ),
        sa.Column(
            "avg_duration",
            sa.Float(),
            nullable=True,
            comment="Средняя длительность сделки (в часах)",
        ),
        sa.Column(
            "med_duration",
            sa.Float(),
            nullable=True,
            comment="Медианная длительность сделки (в часах)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время сохранения записи",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticker_id"],
            ["tickers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trade_stats_created_at"),
        "trade_stats",
        ["created_at"],
        unique=False,
    )

    op.execute(
        sa.text(
            "INSERT INTO markets (name) VALUES (:name1), (:name2)"
        ).bindparams(name1="MOEX", name2="Bybit")
    )

    # Добавляем в таблицу strategies записи macd, smart-supertrend (status=ACTIVE)
    op.execute(
        sa.text(
            """
            INSERT INTO strategies (name, status)
            VALUES (:name1, :status), (:name2, :status)
        """
        ).bindparams(name1="macd", name2="smart-supertrend", status="ACTIVE")
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trade_stats_created_at"), table_name="trade_stats")
    op.drop_table("trade_stats")
    op.drop_index(
        op.f("ix_strategy_params_created_at"), table_name="strategy_params"
    )
    op.drop_table("strategy_params")
    op.drop_index(op.f("ix_signals_created_at"), table_name="signals")
    op.drop_table("signals")
    op.drop_index(op.f("ix_tickers_created_at"), table_name="tickers")
    op.drop_table("tickers")
    op.drop_index(op.f("ix_strategies_created_at"), table_name="strategies")
    op.drop_table("strategies")
    op.drop_index(op.f("ix_markets_created_at"), table_name="markets")
    op.drop_table("markets")
    # ### end Alembic commands ###
