"""add column to backtest jobs

Revision ID: fed2571a1c7d
Revises: 97466257268a
Create Date: 2025-10-01 22:12:44.051408

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fed2571a1c7d"
down_revision: Union[str, None] = "97466257268a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backtest_jobs",
        sa.Column(
            "counts_towards_limit",
            sa.Boolean(),
            nullable=False,
            server_default="TRUE",
            comment="Флаг учета в лимитах",
        ),
        schema="trader_core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "backtest_jobs", "counts_towards_limit", schema="trader_core"
    )
    # ### end Alembic commands ###
