"""mark strategy deleted

Revision ID: dcf984e6071d
Revises: 08b4091a9ad3
Create Date: 2025-09-11 16:33:10.637557

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dcf984e6071d"
down_revision: Union[str, None] = "08b4091a9ad3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "strategies",
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            comment="True если стратегия была удалена пользователем",
            server_default=sa.text("false"),
        ),
        schema="trader_core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("strategies", "is_deleted", schema="trader_core")
    # ### end Alembic commands ###
