"""update strategy_params and trade_stats

Revision ID: 6c95f6ca172e
Revises: f3266ebf0145
Create Date: 2025-03-13 05:49:27.867940

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c95f6ca172e"
down_revision: Union[str, None] = "f3266ebf0145"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "strategy_params",
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="JSON с параметрами стратегии",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "max_drawdown_pct",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="Максимальный % убытка среди проигрышных сделок",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "current_drawdown_streak_pct",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="Максимальный % убытка подряд среди проигрышных сделок",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trade_stats", "current_drawdown_streak_pct")
    op.drop_column("trade_stats", "max_drawdown_pct")
    op.drop_column("strategy_params", "metrics")
    # ### end Alembic commands ###
