"""remove unique key add updated

Revision ID: d246e5058301
Revises: 4e0b6c5c68d8
Create Date: 2025-07-26 19:57:39.079142

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d246e5058301"
down_revision: Union[str, None] = "4e0b6c5c68d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backtest_jobs",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время обновления записи",
        ),
        schema="trader_core",
    )
    op.drop_constraint(
        "backtest_results_job_id_key",
        "backtest_results",
        schema="trader_core",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # удаляем дубли
    op.execute(
        """
        DELETE FROM trader_core.backtest_results a
        USING trader_core.backtest_results b
        WHERE a.job_id = b.job_id
          AND a.ctid < b.ctid;
    """
    )
    op.create_unique_constraint(
        "backtest_results_job_id_key",
        "backtest_results",
        ["job_id"],
        schema="trader_core",
    )
    op.drop_column("backtest_jobs", "updated_at", schema="trader_core")
    # ### end Alembic commands ###
