"""add indexes to backtest jobs strategies

Revision ID: f5d6bb049a9a
Revises: 58b13c079f60
Create Date: 2025-09-21 21:40:58.342740

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5d6bb049a9a"
down_revision: Union[str, None] = "58b13c079f60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_backtest_jobs_strategy",
        "backtest_jobs",
        ["strategy_id", "created_at"],
        unique=False,
        schema="trader_core",
    )
    op.create_index(
        "idx_backtest_jobs_user_sorting",
        "backtest_jobs",
        ["user_id", "created_at", "status"],
        unique=False,
        schema="trader_core",
    )
    # Создаем функциональный индекс через сырой SQL из-за проблем с Alembic и приведением типов
    op.execute(
        """
        CREATE INDEX idx_backtest_results_max_drawdown
        ON trader_core.backtest_results (CAST(metrics->>'max_drawdown_pct' AS numeric))
        WHERE metrics ? 'max_drawdown_pct'
    """
    )
    op.create_index(
        "idx_backtest_results_metrics_gin",
        "backtest_results",
        ["metrics"],
        unique=False,
        schema="trader_core",
        postgresql_using="gin",
    )
    op.execute(
        """
        CREATE INDEX idx_backtest_results_profit_factor
        ON trader_core.backtest_results (CAST(metrics->>'profit_factor' AS numeric))
        WHERE metrics ? 'profit_factor'
    """
    )
    op.execute(
        """
        CREATE INDEX idx_backtest_results_roi
        ON trader_core.backtest_results (COALESCE(CAST(metrics->>'roi' AS numeric), CAST(metrics->>'net_total_profit_pct' AS numeric)))
        WHERE metrics ? 'roi' OR metrics ? 'net_total_profit_pct'
    """
    )
    op.execute(
        """
        CREATE INDEX idx_backtest_results_sharpe_ratio
        ON trader_core.backtest_results (CAST(metrics->>'sharpe_ratio' AS numeric))
        WHERE metrics ? 'sharpe_ratio'
    """
    )
    op.execute(
        """
        CREATE INDEX idx_backtest_results_total_trades
        ON trader_core.backtest_results (CAST(metrics->>'total_trades' AS integer))
        WHERE metrics ? 'total_trades'
    """
    )
    op.execute(
        """
        CREATE INDEX idx_backtest_results_win_rate
        ON trader_core.backtest_results (CAST(metrics->>'win_rate' AS numeric))
        WHERE metrics ? 'win_rate'
    """
    )
    op.create_index(
        "idx_strategies_user_name",
        "strategies",
        ["user_id", "name"],
        unique=True,
        schema="trader_core",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_index(
        "idx_strategies_user_sorting",
        "strategies",
        ["user_id", "is_deleted", "created_at", "name"],
        unique=False,
        schema="trader_core",
        postgresql_where=sa.text("is_deleted = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_strategies_user_sorting",
        table_name="strategies",
        schema="trader_core",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(
        "idx_strategies_user_name",
        table_name="strategies",
        schema="trader_core",
        postgresql_where=sa.text("is_deleted = false"),
    )
    # Удаляем функциональные индексы через сырой SQL
    op.execute(
        "DROP INDEX IF EXISTS trader_core.idx_backtest_results_win_rate"
    )
    op.execute(
        "DROP INDEX IF EXISTS trader_core.idx_backtest_results_total_trades"
    )
    op.execute(
        "DROP INDEX IF EXISTS trader_core.idx_backtest_results_sharpe_ratio"
    )
    op.execute("DROP INDEX IF EXISTS trader_core.idx_backtest_results_roi")
    op.execute(
        "DROP INDEX IF EXISTS trader_core.idx_backtest_results_profit_factor"
    )
    op.drop_index(
        "idx_backtest_results_metrics_gin",
        table_name="backtest_results",
        schema="trader_core",
        postgresql_using="gin",
    )
    op.execute(
        "DROP INDEX IF EXISTS trader_core.idx_backtest_results_max_drawdown"
    )
    op.drop_index(
        "idx_backtest_jobs_user_sorting",
        table_name="backtest_jobs",
        schema="trader_core",
    )
    op.drop_index(
        "idx_backtest_jobs_strategy",
        table_name="backtest_jobs",
        schema="trader_core",
    )
    # ### end Alembic commands ###
