"""add geo ip info

Revision ID: 58b13c079f60
Revises: 06f314d0a1f6
Create Date: 2025-09-18 16:22:46.258847

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "58b13c079f60"
down_revision: Union[str, None] = "06f314d0a1f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_sessions",
        sa.Column(
            "enriched_device_info",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Обогащенная информация об устройстве с GeoIP, парсингом User-Agent и fingerprinting",
        ),
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_sessions", "enriched_device_info", schema="auth")
    # ### end Alembic commands ###
