"""add updated_at column and add desc in strategies

Revision ID: ed7a1f6878b8
Revises: dcf984e6071d
Create Date: 2025-09-12 17:06:38.386335

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ed7a1f6878b8"
down_revision: Union[str, None] = "dcf984e6071d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применяет изменения в базе данных.

    Добавляет колонки updated_at и description, обрабатывает дубликаты
    названий стратегий у одного пользователя и создает уникальное ограничение.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        comment="(datetime) - время обновления записи",
        existing_comment="Время последнего обновления записи",
        existing_server_default=sa.text("now()"),
        schema="auth",
    )
    op.add_column(
        "backtest_results",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время обновления записи",
        ),
        schema="trader_core",
    )
    op.add_column(
        "strategies",
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Описание стратегии",
        ),
        schema="trader_core",
    )
    op.add_column(
        "strategies",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="(datetime) - время обновления записи",
        ),
        schema="trader_core",
    )

    # Обработка дубликатов названий стратегий перед созданием уникального ограничения
    _handle_duplicate_strategy_names()

    op.create_unique_constraint(
        "uq_user_id_name",
        "strategies",
        ["user_id", "name"],
        schema="trader_core",
    )
    # ### end Alembic commands ###


def _handle_duplicate_strategy_names() -> None:
    """Обрабатывает дубликаты названий стратегий у одного пользователя.

    Добавляет к дублирующимся названиям суффиксы в формате (1), (2) и т.д.
    Первая стратегия с данным названием остается без изменений.
    """
    connection = op.get_bind()

    # SQL для поиска дубликатов и их нумерации
    duplicate_query = """
    WITH duplicates AS (
        SELECT 
            id,
            name,
            user_id,
            ROW_NUMBER() OVER (
                PARTITION BY user_id, name 
                ORDER BY created_at ASC, id ASC
            ) as row_num
        FROM trader_core.strategies
    ),
    duplicates_to_update AS (
        SELECT 
            id,
            name,
            row_num
        FROM duplicates 
        WHERE row_num > 1
    )
    SELECT id, name, row_num FROM duplicates_to_update;
    """

    result = connection.execute(sa.text(duplicate_query))
    duplicates = result.fetchall()

    # Обновляем названия дубликатов
    for strategy_id, original_name, row_num in duplicates:
        new_name = f"{original_name} ({row_num})"

        update_query = """
        UPDATE trader_core.strategies 
        SET name = :new_name 
        WHERE id = :strategy_id
        """

        connection.execute(
            sa.text(update_query),
            {"new_name": new_name, "strategy_id": strategy_id},
        )


def downgrade() -> None:
    """Откатывает изменения в базе данных."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_user_id_name", "strategies", schema="trader_core", type_="unique"
    )
    op.drop_column("strategies", "updated_at", schema="trader_core")
    op.drop_column("strategies", "description", schema="trader_core")
    op.drop_column("backtest_results", "updated_at", schema="trader_core")
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        comment="Время последнего обновления записи",
        existing_comment="(datetime) - время обновления записи",
        existing_server_default=sa.text("now()"),
        schema="auth",
    )
    # ### end Alembic commands ###
