"""add snapshot and simulation params to backtest_jobs

Revision ID: f9f5fd036065
Revises: ec3406182df0
Create Date: 2025-09-06 17:26:51.806843

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f9f5fd036065"
down_revision: Union[str, None] = "ec3406182df0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backtest_jobs",
        sa.Column(
            "strategy_definition_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Снапшот AST стратегии",
        ),
        schema="trader_core",
    )
    op.add_column(
        "backtest_jobs",
        sa.Column(
            "simulation_params",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Параметры симуляции",
        ),
        schema="trader_core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("backtest_jobs", "simulation_params", schema="trader_core")
    op.drop_column(
        "backtest_jobs", "strategy_definition_snapshot", schema="trader_core"
    )
    # ### end Alembic commands ###
