"""create system indicators table

Revision ID: ec3406182df0
Revises: febb370167ba
Create Date: 2025-09-06 15:24:08.982720

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ec3406182df0"
down_revision: Union[str, None] = "febb370167ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_indicators",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.String(length=50),
            nullable=False,
            comment="Уникальное имя семейства индикаторов",
        ),
        sa.Column(
            "display_name",
            sa.String(length=100),
            nullable=False,
            comment="Человекочитаемое название индикатора",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Описание индикатора для пользователей",
        ),
        sa.Column(
            "category",
            sa.String(length=50),
            nullable=False,
            comment="Категория индикатора",
        ),
        sa.Column(
            "complexity",
            sa.String(length=20),
            nullable=False,
            comment="Уровень сложности индикатора",
        ),
        sa.Column(
            "parameters_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Схема параметров и их ограничения",
        ),
        sa.Column(
            "output_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Схема выходных значений",
        ),
        sa.Column(
            "key_template",
            sa.String(length=200),
            nullable=False,
            comment="Шаблон генерации ключа",
        ),
        sa.Column(
            "is_enabled",
            sa.Boolean(),
            nullable=False,
            comment="Статус активности индикатора",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="trader_core",
    )
    op.create_table(
        "users_indicators",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "indicator_key",
            sa.String(length=100),
            nullable=False,
            comment="Уникальный ключ экземпляра индикатора",
        ),
        sa.Column(
            "name",
            sa.String(length=50),
            nullable=False,
            comment="Имя семейства индикаторов",
        ),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Параметры экземпляра индикатора",
        ),
        sa.Column(
            "is_hot",
            sa.Boolean(),
            nullable=False,
            comment="Флаг для RT-калькулятора",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trader_core",
    )
    op.create_index(
        op.f("ix_trader_core_users_indicators_indicator_key"),
        "users_indicators",
        ["indicator_key"],
        unique=True,
        schema="trader_core",
    )
    op.drop_index(
        "ix_trader_core_indicators_indicator_key",
        table_name="indicators",
        schema="trader_core",
    )
    op.drop_table("indicators", schema="trader_core")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indicators",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "indicator_key",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
            comment="Уникальный ключ индикатора, например, 'sma_20'",
        ),
        sa.Column(
            "name",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
            comment="Имя семейства индикаторов, например, 'SMA'",
        ),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
            comment="Параметры индикатора в формате JSON",
        ),
        sa.Column(
            "is_hot",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Флаг для RT-калькулятора",
        ),
        sa.PrimaryKeyConstraint("id", name="indicators_pkey"),
        schema="trader_core",
    )
    op.create_index(
        "ix_trader_core_indicators_indicator_key",
        "indicators",
        ["indicator_key"],
        unique=True,
        schema="trader_core",
    )
    op.drop_index(
        op.f("ix_trader_core_users_indicators_indicator_key"),
        table_name="users_indicators",
        schema="trader_core",
    )
    op.drop_table("users_indicators", schema="trader_core")
    op.drop_table("system_indicators", schema="trader_core")
    # ### end Alembic commands ###
