"""update trade_stats

Revision ID: f3266ebf0145
Revises: d602d581b5c7
Create Date: 2025-03-11 19:22:55.935622

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f3266ebf0145"
down_revision: Union[str, None] = "d602d581b5c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trade_stats",
        sa.Column(
            "strategy_name",
            sa.String(length=128),
            nullable=False,
            comment="FK на таблицу strategies",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "ticker",
            sa.String(length=128),
            nullable=False,
            comment="FK на таблицу tickers",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "position_type",
            sa.String(),
            nullable=True,
            comment="Тип позиции (long/short/...)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "entry_price",
            sa.Numeric(precision=20, scale=8),
            nullable=True,
            comment="Цена входа в сделку",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "exit_price",
            sa.Numeric(precision=20, scale=8),
            nullable=True,
            comment="Цена выхода из сделки",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "stop_loss",
            sa.Numeric(precision=20, scale=8),
            nullable=True,
            comment="Уровень стоп-лосса",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "profit_pct",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="Прибыль/убыток сделки в %",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "profit_abs",
            sa.Numeric(precision=20, scale=8),
            nullable=True,
            comment="Абсолютная прибыль/убыток",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "is_win",
            sa.Boolean(),
            nullable=True,
            comment="Флаг выигрышной сделки",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "duration_hours",
            sa.Float(),
            nullable=True,
            comment="Длительность сделки в часах",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "total_profit_pct",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="Суммарная прибыль в % (по всем сделкам)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "total_profit_abs",
            sa.Numeric(precision=20, scale=8),
            nullable=True,
            comment="Суммарная прибыль в абсолюте (по всем сделкам)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "avg_profit_pct",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="Средняя прибыль в % (по всем сделкам)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "consecutive_wins",
            sa.Integer(),
            nullable=True,
            comment="Текущая серия выигрышных сделок",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "consecutive_losses",
            sa.Integer(),
            nullable=True,
            comment="Текущая серия проигрышных сделок",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "best_trade_pct",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="Лучшая сделка (в %)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "worst_trade_pct",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="Худшая сделка (в %)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "sum_win_abs",
            sa.Numeric(precision=20, scale=8),
            nullable=True,
            comment="Сумма выигрышей (абсолютная)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "sum_loss_abs",
            sa.Numeric(precision=20, scale=8),
            nullable=True,
            comment="Сумма убытков (абсолютная)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "sum_win_pct",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="Сумма процентов по выигрышным сделкам",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "sum_loss_pct",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="Сумма процентов по убыточным сделкам (отрицательная)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "avg_win_pct",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="Средний % прибыли среди выигрышных сделок",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "avg_loss_pct",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="Средний % убытка среди проигрышных сделок",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "total_duration_hours",
            sa.Float(),
            nullable=True,
            comment="Суммарное время всех сделок (в часах)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "avg_duration_hours",
            sa.Float(),
            nullable=True,
            comment="Среднее время сделки (в часах)",
        ),
    )
    op.alter_column(
        "trade_stats",
        "total_trades",
        existing_type=sa.INTEGER(),
        comment="Всего сделок",
        existing_comment="Всего сделок за период",
        existing_nullable=True,
    )
    op.alter_column(
        "trade_stats",
        "wins",
        existing_type=sa.INTEGER(),
        comment="Количество выигрышных сделок",
        existing_comment="Кол-во выигрышных сделок",
        existing_nullable=True,
    )
    op.alter_column(
        "trade_stats",
        "losses",
        existing_type=sa.INTEGER(),
        comment="Количество проигрышных сделок",
        existing_comment="Кол-во проигрышных сделок",
        existing_nullable=True,
    )
    op.alter_column(
        "trade_stats",
        "profit_factor",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        comment="Profit Factor (отношение суммы выигрышей к сумме убытков)",
        existing_comment="Profit Factor",
        existing_nullable=True,
    )
    op.drop_constraint(
        "trade_stats_strategy_id_fkey", "trade_stats", type_="foreignkey"
    )
    op.drop_constraint(
        "trade_stats_ticker_id_fkey", "trade_stats", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_trade_stats_ticker_symbol",
        "trade_stats",
        "tickers",
        ["ticker"],
        ["symbol"],
    )
    op.create_foreign_key(
        "fk_trade_stats_strategy_name",
        "trade_stats",
        "strategies",
        ["strategy_name"],
        ["name"],
    )
    op.drop_column("trade_stats", "max_drawdown_abs")
    op.drop_column("trade_stats", "calmar")
    op.drop_column("trade_stats", "end_date")
    op.drop_column("trade_stats", "avg_duration")
    op.drop_column("trade_stats", "ticker_id")
    op.drop_column("trade_stats", "start_date")
    op.drop_column("trade_stats", "initial_balance")
    op.drop_column("trade_stats", "avg_loss")
    op.drop_column("trade_stats", "final_balance")
    op.drop_column("trade_stats", "strategy_id")
    op.drop_column("trade_stats", "roi")
    op.drop_column("trade_stats", "med_duration")
    op.drop_column("trade_stats", "avg_win")
    op.drop_column("trade_stats", "pnl")
    op.drop_column("trade_stats", "max_drawdown_pct")
    op.drop_column("trade_stats", "std_ret")
    op.drop_column("trade_stats", "sharpe_ratio")
    op.drop_column("trade_stats", "avg_trade_profit")
    op.drop_column("trade_stats", "avg_ret")
    op.drop_column("trade_stats", "median_ret")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trade_stats",
        sa.Column(
            "median_ret",
            sa.NUMERIC(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
            comment="Медиана доходности сделки (%)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "avg_ret",
            sa.NUMERIC(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
            comment="Средняя доходность сделки (%)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "avg_trade_profit",
            sa.NUMERIC(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
            comment="Средняя прибыль на сделку (в денежном выражении)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "sharpe_ratio",
            sa.NUMERIC(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
            comment="Sharpe Ratio (упрощенный)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "std_ret",
            sa.NUMERIC(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
            comment="Стандартное отклонение доходности сделки (%)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "max_drawdown_pct",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
            comment="Макс. просадка в процентах",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "pnl",
            sa.NUMERIC(precision=20, scale=8),
            autoincrement=False,
            nullable=True,
            comment="Прибыль/убыток сделки",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "avg_win",
            sa.NUMERIC(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
            comment="Средний выигрыш",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "med_duration",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="Медианная длительность сделки (в часах)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "roi",
            sa.NUMERIC(precision=10, scale=4),
            autoincrement=False,
            nullable=True,
            comment="ROI (%)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "strategy_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="FK на таблицу strategies",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "final_balance",
            sa.NUMERIC(precision=20, scale=8),
            autoincrement=False,
            nullable=True,
            comment="Конечный баланс в конце периода",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "avg_loss",
            sa.NUMERIC(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
            comment="Средний проигрыш",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "initial_balance",
            sa.NUMERIC(precision=20, scale=8),
            autoincrement=False,
            nullable=True,
            comment="Начальный баланс в начале периода",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "start_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Начало периода (например, начало бэктеста)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "ticker_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="FK на таблицу tickers",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "avg_duration",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="Средняя длительность сделки (в часах)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "end_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Конец периода (например, конец бэктеста)",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "calmar",
            sa.NUMERIC(precision=8, scale=4),
            autoincrement=False,
            nullable=True,
            comment="Calmar Ratio",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "max_drawdown_abs",
            sa.NUMERIC(precision=20, scale=8),
            autoincrement=False,
            nullable=True,
            comment="Макс. просадка в абсолюте",
        ),
    )
    op.drop_constraint(
        "fk_trade_stats_ticker_symbol", "trade_stats", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_trade_stats_strategy_name", "trade_stats", type_="foreignkey"
    )
    op.create_foreign_key(
        "trade_stats_ticker_id_fkey",
        "trade_stats",
        "tickers",
        ["ticker_id"],
        ["id"],
    )
    op.create_foreign_key(
        "trade_stats_strategy_id_fkey",
        "trade_stats",
        "strategies",
        ["strategy_id"],
        ["id"],
    )
    op.alter_column(
        "trade_stats",
        "profit_factor",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        comment="Profit Factor",
        existing_comment="Profit Factor (отношение суммы выигрышей к сумме убытков)",
        existing_nullable=True,
    )
    op.alter_column(
        "trade_stats",
        "losses",
        existing_type=sa.INTEGER(),
        comment="Кол-во проигрышных сделок",
        existing_comment="Количество проигрышных сделок",
        existing_nullable=True,
    )
    op.alter_column(
        "trade_stats",
        "wins",
        existing_type=sa.INTEGER(),
        comment="Кол-во выигрышных сделок",
        existing_comment="Количество выигрышных сделок",
        existing_nullable=True,
    )
    op.alter_column(
        "trade_stats",
        "total_trades",
        existing_type=sa.INTEGER(),
        comment="Всего сделок за период",
        existing_comment="Всего сделок",
        existing_nullable=True,
    )
    op.drop_column("trade_stats", "avg_duration_hours")
    op.drop_column("trade_stats", "total_duration_hours")
    op.drop_column("trade_stats", "avg_loss_pct")
    op.drop_column("trade_stats", "avg_win_pct")
    op.drop_column("trade_stats", "sum_loss_pct")
    op.drop_column("trade_stats", "sum_win_pct")
    op.drop_column("trade_stats", "sum_loss_abs")
    op.drop_column("trade_stats", "sum_win_abs")
    op.drop_column("trade_stats", "worst_trade_pct")
    op.drop_column("trade_stats", "best_trade_pct")
    op.drop_column("trade_stats", "consecutive_losses")
    op.drop_column("trade_stats", "consecutive_wins")
    op.drop_column("trade_stats", "avg_profit_pct")
    op.drop_column("trade_stats", "total_profit_abs")
    op.drop_column("trade_stats", "total_profit_pct")
    op.drop_column("trade_stats", "duration_hours")
    op.drop_column("trade_stats", "is_win")
    op.drop_column("trade_stats", "profit_abs")
    op.drop_column("trade_stats", "profit_pct")
    op.drop_column("trade_stats", "stop_loss")
    op.drop_column("trade_stats", "exit_price")
    op.drop_column("trade_stats", "entry_price")
    op.drop_column("trade_stats", "position_type")
    op.drop_column("trade_stats", "ticker")
    op.drop_column("trade_stats", "strategy_name")
    # ### end Alembic commands ###
