"""add stability score metric

Revision ID: d027cebd3d0e
Revises: 6c95f6ca172e
Create Date: 2025-03-21 20:08:38.308247

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d027cebd3d0e"
down_revision: Union[str, None] = "6c95f6ca172e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trade_stats",
        sa.Column(
            "profit_std_dev",
            sa.Float(),
            nullable=True,
            comment="Стандартное отклонение доходности сделок",
        ),
    )
    op.add_column(
        "trade_stats",
        sa.Column(
            "stability_score",
            sa.Float(),
            nullable=True,
            comment="Комплексная метрика стабильности стратегии (0-100)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trade_stats", "stability_score")
    op.drop_column("trade_stats", "profit_std_dev")
    # ### end Alembic commands ###
